### ISSUE TITLE
Xibo Exchange: release task list

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2735]
We need to address the following before release:
 - [x] logo for the connector
 - [x] add an icon to the results to indicate when one is from the exchange
 - [x] confirm we want to call it Xibo Exchange
